# Generated by Django 4.2.3 on 2023-09-23 14:44

from django.db import migrations, models
import news.models.news_model


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(
                validators=[news.models.news_model.word_counter]
            ),
        ),
    ]
